### ISSUE TITLE
Add additional form integrations to front page

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/site#39]
I'd like to see us re-arrange the way integration logos are displayed on the front page for increased and improved 3rd-party brand acknowledgement.

![image](https://user-images.githubusercontent.com/1034109/97996782-cd8c3e00-1dad-11eb-842c-8e8d7420543d.png)

At minimum, we need to get WP Forms added but it'd be best if we also got Formidable Forms shown there.

We also have an integration with Paid Memberships Pro so perhaps it could be done in a way that's more flexible and allows for more brands to be added.

**Comment by SDavisMedia** [comment]
@pippinsplugins Would the overall goal to be feeding _all_ integrations to the area? Even though these are the only integrations that existed at the time of building this, I created the section because I felt like those were three strong, recognizable brands that we'd highlight, even if we didn't highlight others. Think of it like a selected list of brands in a logo cloud, more so than dynamic integrations list. We do the same with EDD:

![Screenshot_2020-11-06 Easy Digital Downloads - Sell Digital Downloads With WordPress](https://user-images.githubusercontent.com/2359131/98412256-3b9a6480-203d-11eb-9f67-8efd3ce21963.png)

So if the goal is to treat it as an actual integrations area, then I'll just create a custom post type and let them populate as added. Is that what you'd prefer?

**Comment by SDavisMedia** [comment]
Actually, you already answered the question. Post type it is.

**Comment by pippinsplugins** [comment]
Yep, that's exactly what I'd love to see. We don't have many integrations right now but we'll continue to add them in the future so let's make it flexible.

**Comment by thisisjoewells** [comment]
Hi y'all, let me know if I can help with this. Note Google has a new Google Calendar logo out. I'll try to get a new file...sometimes it's actually hard to get Google brand assets, and you just have to snag something off Google search.

I'm trying to build out the 'infrastructure' to keep tabs on third party logos. I just moved these files and a sheet to the new 'Marketing' Shared Drive area:

Logo tracking sheet:
https://docs.google.com/spreadsheets/d/1y-t5vvd1GqrIMbkMKcJyBqg_QPRKz1bH0kYEYyjKWnw/edit?usp=sharing

The folder with some compiled brand assets from third-parties:
https://drive.google.com/drive/folders/1vXTZEZDzgWFRxevyZL1y_CybR0kAaekQ?usp=sharing

**Comment by SDavisMedia** [comment]
@thisisjoewells It's definitely hard to get quality Google assets. It was a serious struggle find and choosing something for the Sugar Calendar integration.

I don't know exactly what I'm going to do here yet, but I shouldn't need much help as this will be all development. When it's all said and done, though, it'll just be adding/adjusting post entries and adding a featured image (logo). If you want certain logos changed during that process, let me know. Otherwise I'll just do all the dev and then folks can have at it without my oversight.

**Comment by thisisjoewells** [comment]
Hi @SDavisMedia - I had a Basecamp reminder to check back in on this issue. And I was updating some of my routine logo audits today.

So, I put together a re-sized collection of logos that could be used for this new home page area. I have Tiny-PNG'ed vesions at 800x800 and 400x400 (they are 400x400 now).

**All here >>** https://drive.google.com/drive/folders/1pGO0pdxwluI3lgbFPqYvXlOvKZ2taODu

It includes a few new ones to replace with existing ones:
- Google Calendar
- Gravity Forms ([their logo guidelines](https://www.lingoapp.com/70269/s/RymA5x/?kit_token=U44F0r1nCHzzOH0oLf2sR8sKeeZfCyI8V_693_OzAVw&v=0) seem to request orange, dark gray, or white-reverse, I figure their orange clashes with ours, so dark gray?)

It includes new ones that are planned (WPForms) and that we might want to add their at some point:
- WPForms
- Stripe
- WooCommerce
- WP All Import

You may have different or better ideas on how to do some of these treatments, I got particularly stuck on the best way to do WP All Import. So, there is a layered AffPhoto file there so you can do whatever changes you want quickly (sugarcal-homepage-integrations.afphoto)

A lot of these folks don't have the most abundant brand assets pages with instructions. After being on many of these types of pages the last few months...I again have to give you the props!! 

**Sandhills brand asset pages are for sure the best in the WP space!!** 🙌

**Comment by pippinsplugins** [comment]
Joe's comment just reminded me too that we should definitely be getting WooCommerce listed as well since we have a Woo integration in Event Ticketing.

**Comment by SDavisMedia** [comment]
Working on this now. We don't have to discuss too much about which logos go where here on GitHub. This issue is about the code/functionality behind the output. Once done, you'll be able to populate it with whatever you want and update it any time without my involvement, unless there's an issue. So those details can be managed over on Basecamp, if they need management.

Thanks for the kind words about the brand assets pages, @thisisjoewells.

**Comment by SDavisMedia** [comment]
This is up on the [live](https://sugarcalendar.com/wp-admin/edit.php?post_type=integration) [site](https://sugarcalendar.com/) as well as staging. If you want to play with it, or start adding integrations, please consider [using staging first](http://s31779.p27.sites.pressdns.com/wp-admin/edit.php?post_type=integration).

These are meant to be a direct replacement for the original display. They don't link to anything or do anything different than what they did before. I'm simply covering what's meant to be changed in this issue.

Integration entries need a title, a short description, and a featured image. Once published, they'll show up on the front page. Columns will adjust as best they can based on the number of integrations being displayed.

If you ever create an integration and it is literally anything other than a square image, a single line title, and a two line description, please either talk to me about why we should make display changes or make sure your content is as consistent with the other integrations as possible. If an image should be made for an integration, Joe and I are more than capable of whipping one up. Just say the word.

If you're happy with this, @pippinsplugins, you're free to close the issue.
